In [ ]:
#importing libraries
#load dataset
#handling missing data
#handling categorical data
#split dataset into train and test
#feature scaling

In [ ]:
import pandas as pd #used for hadnling datasets
import numpy as np #used for handling numbers
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer


from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import os
os.chdir("/content/drive/My Drive/ML Practical/ML Practicals/data/")
df = pd.read_csv("first_sample.csv")
df

Mounted at /content/drive

   Region   Age   Income Online Shopper
0   India  49.0  45000.0            Yes
1  Brazil  48.0  80000.0             No
2     USA  35.0  56600.0            Yes
3   India  30.0      NaN             No
4     USA   NaN  45120.0            Yes
5  Brazil  39.0  24570.0             No
6   India  46.0  59520.0             No
7  Brazil  50.0  53254.0            Yes
8   India  38.0  78546.0            Yes

In [ ]:
df.Age = df.Age.fillna(df.Age.mean())
df.Income = df.Income.fillna(df.Income.mean())
df

   Region     Age    Income Online Shopper
0   India  49.000  45000.00            Yes
1  Brazil  48.000  80000.00             No
2     USA  35.000  56600.00            Yes
3   India  30.000  55326.25             No
4     USA  41.875  45120.00            Yes
5  Brazil  39.000  24570.00             No
6   India  46.000  59520.00             No
7  Brazil  50.000  53254.00            Yes
8   India  38.000  78546.00            Yes

In [ ]:
X = df.iloc[:,[0,1,2]].values #inde
y = df.iloc[:,3].values #dep
print(X)
print(y)

[['India' 49.0 45000.0]
 ['Brazil' 48.0 80000.0]
 ['USA' 35.0 56600.0]
 ['India' 30.0 55326.25]
 ['USA' 41.875 45120.0]
 ['Brazil' 39.0 24570.0]
 ['India' 46.0 59520.0]
 ['Brazil' 50.0 53254.0]
 ['India' 38.0 78546.0]]
['Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes']

In [ ]:
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3]) # load into the original values/DF
print(X)

[['India' 49.0 45000.0]
 ['Brazil' 48.0 80000.0]
 ['USA' 35.0 56600.0]
 ['India' 30.0 55326.25]
 ['USA' 41.875 45120.0]
 ['Brazil' 39.0 24570.0]
 ['India' 46.0 59520.0]
 ['Brazil' 50.0 53254.0]
 ['India' 38.0 78546.0]]

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = ct.fit_transform(X)
X = np.array(X)
print(X)

[[0.0 1.0 0.0 49.0 45000.0]
 [1.0 0.0 0.0 48.0 80000.0]
 [0.0 0.0 1.0 35.0 56600.0]
 [0.0 1.0 0.0 30.0 55326.25]
 [0.0 0.0 1.0 41.875 45120.0]
 [1.0 0.0 0.0 39.0 24570.0]
 [0.0 1.0 0.0 46.0 59520.0]
 [1.0 0.0 0.0 50.0 53254.0]
 [0.0 1.0 0.0 38.0 78546.0]]

In [ ]:
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 0 1 0 1 0 0 1 1]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [ ]:
print('X_train.shape: ', X_train.shape)
print('X_test.shape:  ', X_test.shape)
print('y_train.shape: ', y_train.shape)
print('y_test.shape:  ', y_test.shape)

X_train.shape:  (7, 5)
X_test.shape:   (2, 5)
y_train.shape:  (7,)
y_test.shape:   (2,)